---
title: "scratch-file"
author: "Sven Maurice Morlock"
date: "`r Sys.Date()`"
output:
  pdf_document: default
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library(this.path)
#===============================================================================
path_attic_folder <- this.dir()
path_project_root <- dirname(path_attic_folder)
source(file.path(path_project_root, "R", "segmentation.R"))
```


## Landscape Tables

```{r}

clusters_2021_aic %>% kable(longtable = T, booktabs = T, format = "latex") %>% kable_styling(latex_options = c("repeat_header")) %>%
  landscape()
```